kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: example2
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: ''
    openshift.io/requester: kamkie
    openshift.io/sa.scc.mcs: 's0:c26,c10'
    openshift.io/sa.scc.supplemental-groups: 1000670000/10000
    openshift.io/sa.scc.uid-range: 1000670000/10000
spec:
  finalizers:
    - kubernetes

