apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example1
  namespace: openshift-gitops
spec:
  destination:
    namespace: example1
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: .
    repoURL: 'https://github.com/kamkie/argocd-examples.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
