apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example1
  namespace: argocd
spec:
  destination:
    namespace: example1
    server: 'https://kubernetes.default.svc'
  project: example1
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: .
    repoURL: 'git@github.com:kamkie/argocd-examples.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
