apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example3
  namespace: openshift-operators
spec:
  destination:
    namespace: example2
    server: 'https://kubernetes.default.svc'
  project: example1
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: .
    repoURL: 'https://github.com/kamkie/argocd-examples2.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
